import { Header } from '@/components/Header'
import Head from 'next/head'

import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Blog Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
     

    <div className='w-full max-w-[1120px] flex flex-col mx-auto pb-12'>
      <Header/>

      <div className='flex flex-1 h-[334px]'>
          <Image 
            src="https://images.unsplash.com/photo-1564865878688-9a244444042a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
            alt=""
            width={544}
            height={334}
          />
      </div>

    </div>

    </>
  )
}
